<div class="max-w-7xl mx-auto py-12 px-4 sm:py-16 sm:px-6 lg:px-8">
    <div class="max-w-7xl mx-auto text-gray-600 text-lg">
      <div class="text-center text-4xl text-gray-600">Benutzerhinweise [Entwurf]</div>
      <div class="pt-16 font-extrabold">Welche Daten wurden in der Datenbank erfasst?</div>
      <div class="pt-2">Über die Datenbank sind grundsätzlich alle via <a rel="external" href="https://anno.onb.ac.at/" class="text-teal-400">AustriaN Newspapers Online</a> (ANNO) zugänglichen Wiener Zeitungen mit einem Beitrag gewürdigten Ereignisse mit Brahms-Bezug abrufbar. Dies bedeutet, dass auch im Ausland Stattgefundenes (Aufführungen, Auszeichnungen, Zusammenkünfte o. Ä.) gefunden werden kann, sofern in einem hier ausgewerteten Medium darüber berichtet wurde.</div>
  
      <div class="pt-4 font-extrabold">Aufbau der Datenbanksuche</div>
      <div class="pt-2">
        Die beiden Hauptkategorien nach welchen die gesammelten Daten gefiltert werden können, Personen und Werke werden bereits im Drop-down Menü ersichtlich. Wählen Sie eines der beiden Felder aus, können Sie sämtliche in den Daten erwähnten Personen beziehungsweise Werke einsehen. Sofern vorhanden, sehen Sie bei den alphabetisch aufgelisteten Personen auf einen Blick den vollständigen Namen, die Lebensdaten sowie in welcher Funktion die Person an der Aufführung von Brahms' Werken beteiligt war. Folgen Sie dem Pfad zu den Details, erhalten Sie noch genauere Angaben wie alternative Namen, Geburts- und Sterbeort. Weiters können Sie auf etwaige zu den Personen vorhandene biografische Artikel im <a rel="external" href="https://www.musiklexikon.ac.at/ml?frames=no" class="text-teal-400">Österreichischen Musiklexikon online</a> (OeML), dem <a rel="external" href="https://www.biographien.ac.at/oebl?frames=yes" class="text-teal-400">Österreichischen Biografischen Lexikon</a> (OeBL), dem
        <a rel="external" href="https://bmlo.de/" class="text-teal-400">Bayerischen Musiker-Lexikon online</a>
        (BMLO), dem <a rel="external" href="http://www.bruckner-online.at/?page_id=1259" class="text-teal-400">Anton Bruckner Lexikon online</a> (ABLO) und anderen zugreifen. Die Personen sind außerdem, sofern ein entsprechender Eintrag vorhanden war, mit dem Normdatensatz der <a rel="external" href="https://www.dnb.de/DE/Professionell/Standardisierung/GND/gnd_node.html" class="text-teal-400">Gemeinsamen Normdatei</a> (GND) verknüfpt. Die Werkdaten hingegen sind automatisch aufsteigend nach der Opusnummer geordnet und beinhalten zunächst den Titel des Werkes und das Präfix (Opus, Werk ohne Opuszahl, posthumes Werk, posthumes Werk ohne Opuszahl) gefolgt von der Opusnummer. Ein Blick auf die Details eröffnet hier eine Auflistung verschiedener Werkfassungen, sofern vorhanden, und die Besetzung. Des Weiteren finden Sie eine Übersicht über alle erfassten Erwähnungen des Werkes, auf die Sie wiederum via Details einzeln zugreifen können. Der Link zum Portal
        <a rel="external" href="https://anno.onb.ac.at/" class="text-teal-400">AustriaN Newspapers Online</a> (ANNO) der ÖNB, ermöglicht Ihnen auch die Lektüre des Zeitungstextes, welcher dem Datenbankeintrag zugrunde liegt.
      </div>
      <div class="pt-4 font-extrabold">Welche Daten aus den Zeitungsbeiträgen wurden erfasst?</div>
      <div class="pt-2">In den Einträgen sind lediglich jene Informationen verzeichnet, die aus dem jeweiligen Zeitungstext, auf welchem sie basieren, ablesbar sind. Dies heißt, sofern in einer spezifischen Vorankündigung / Rezension beispielsweise kein Aufführungsort verzeichnet ist, wurde dieser auch nicht aus eventuell bestehenden Daten zu dem Ereignis ergänzt. Solche fehlenden Informationen können jedoch oftmals aus korrespondierenden Beiträgen in anderen Medien abgelesen werden. Bitte beachten sie jedoch, dass in diesem Fall der Eintrag nicht bei einer Suchanfrage aufscheinen würde und stellen Sie sicher, dass Sie mehrere der zur Verfügung stehenden Parameter in Ihre Suche mit einbeziehen, um ein möglichst vollständiges Ergebnis zu erhalten.</div>
  
      <div class="pt-4 font-extrabold">Wie funktioniert die Suche in der Datenbank?</div>
      <div class="pt-2">Die erfassten Daten aus Wiener Zeitungen können in der Datenbanksuche zum einen mittels <i>Volltextsuche</i> durchsucht werden, bei der Sie nach einem oder mehreren Begriffen eingeben und noch auswählen können, ob Sie die Suche auf Rezensionen und Vorankündigungen beschränken möchten. Zusätzlich können Sie den Zeitrahmen festlegen, in welchem Sie die Suche durchführen möchten.</div>
      <div class="pt-2">Zum anderen besteht zusätzlich die Möglichkeit einer <i>erweiterten Suche</i>, bei welcher Ihnen Suchparameter [die Suchparameter „Werk“, „Besetzung“, „Veranstaltungsort“, „Beteiligte Personen / Körperschaften“, „Person beteiligt als / mit“, „Rubrik“ und „Quelle“] zur Verfügung [stehen]. Diese können Sie einzeln benutzen und so alle darunter verzeichneten Einträge einsehen oder im Zuge einer kombinierten Suche mittels der zur Verfügung stehenden Kategorien weiter präzisieren. Ebenso besteht die Möglichkeit, die erweiterte Suche mit einer Volltextsuche zu verbinden, um die Suchergebnisse entsprechend zu filtern.</div>
  
      <div class="py-4">(Stand: August 2022)</div>
    </div>
  </div>
  